/* Read-only black-box regression. Every browser URL is fulfilled locally or aborted.
 * Usage: NODE mobile-regression.cjs --source /absolute/release --out /absolute/result.json
 * Exit 1 = failed acceptance assertions; exit 2 = harness/setup error.
 */
const fs=require('node:fs'), path=require('node:path'), crypto=require('node:crypto'), assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const arg=(name,fallback)=>{const i=process.argv.indexOf(name);return i<0?fallback:process.argv[i+1]};
const source=path.resolve(arg('--source',path.join(__dirname,'..')));
const out=path.resolve(arg('--out',path.join(require('node:os').tmpdir(),'roadbook-regression-results.json')));
// Snapshot source in memory before launch: a concurrent product edit cannot mix versions in this run.
const assets=new Map(fs.readdirSync(source).filter(n=>/\.(js|css|html)$/.test(n)).map(n=>[n,fs.readFileSync(path.join(source,n))]));
const sha=Object.fromEntries([...assets].map(([n,b])=>[n,crypto.createHash('sha256').update(b).digest('hex')]));
const K='drive-timeline-trip-v1', SK='drive-timeline-snapshots-v1';
const origin={name:'本地草稿起点',latitude:29,longitude:106,poiId:'ORIGIN'};
const loc=(name,n=0)=>({name,latitude:30+n,longitude:110+n,poiId:name});
const route=(n=900)=>({durationSeconds:n,distanceMeters:n,provider:'fixture',strategy:'highway',polyline:[]});
const stop=(name='地点A',n=0)=>({id:'stop'+n,location:loc(name,n),searchText:name,route:route(),elevationMeters:100,selectedStayButtons:[],stayMode:'duration'});
const trip=(stops=[stop()])=>({schemaVersion:2,startLocation:origin,startSearchText:origin.name,initialDepartureTime:'2030-10-01T00:00:00Z',destinations:stops});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve}};
async function until(f,message,ms=3500){const end=Date.now()+ms;while(Date.now()<end){if(await f())return;await sleep(30)}throw new Error('HARNESS wait: '+message)}
let browser;const results=[];
async function fixture(options={}){
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:3,serviceWorkers:'block'});
 const calls=[],blocked=[],errors=[],requestFailures=[]; const page=await context.newPage();page.setDefaultTimeout(4000);page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>requestFailures.push({url:r.url(),error:r.failure()?.errorText}));
 await context.addInitScript(({seed,K})=>{if(!sessionStorage.getItem('qa-seeded')){localStorage.clear();localStorage.setItem(K,JSON.stringify(seed));localStorage.setItem('drive-timeline-elevation-cache-v1',JSON.stringify({'29.0000,106.0000':100}));sessionStorage.setItem('qa-seeded','1')}}, {seed:options.seed||trip(),K});
 await context.route('**/*',async r=>{
  const u=new URL(r.request().url());const pathname=u.pathname;
  try{
   if(u.hostname!=='review.test'){blocked.push(u.href);await r.abort();return}
   if(pathname==='/config.js'){await r.fulfill({contentType:'application/javascript',body:`globalThis.DRIVE_AI_ENABLED=${!!options.ai};globalThis.DRIVE_API_BASE_URL='';`});return}
   if(pathname.startsWith('/api/')){
    let body={};try{body=r.request().postDataJSON()||{}}catch{}
    const call={path:pathname,query:Object.fromEntries(u.searchParams),body,at:Date.now()};calls.push(call);
    let response=options.api?await options.api(call):undefined;
    if(response===undefined){if(pathname==='/api/poi')response={pois:[loc(u.searchParams.get('keywords'))]};else if(pathname==='/api/route')response=route();else if(pathname==='/api/elevation')response={elevationMeters:100};else if(pathname==='/api/scenic-analysis')response={analysis:{review:'隔离测试评价'}};else response={};}
    if(response?.abort){await r.abort();return}
    await r.fulfill({status:response?.status||200,contentType:'application/json',body:JSON.stringify(response?.json||response)});return;
   }
   const name=pathname==='/'?'index.html':pathname.slice(1);const content=assets.get(name);
   if(!content){blocked.push(u.href);await r.abort();return}
   await r.fulfill({contentType:name.endsWith('.js')?'application/javascript':name.endsWith('.css')?'text/css':'text/html',body:content});
  }catch(e){if(!/closed|cancel|handled|abort|Invalid InterceptionId/i.test(e.message))errors.push('route: '+e.message)}
 });
 if(options.clock)await page.clock.install();
 await page.goto('https://review.test/'+(options.hash||''),{waitUntil:'domcontentloaded'});
 await page.locator('[data-place-input]').first().waitFor({state:'attached'});await sleep(100);
 return {page,context,calls,blocked,errors,requestFailures,read:()=>page.evaluate(K=>JSON.parse(localStorage.getItem(K)),K),close:()=>context.close()};
}
async function test(name,fn){if(arg('--filter','')&&!name.includes(arg('--filter','')))return;const started=Date.now();let f;try{await fn(async o=>(f=await fixture(o)));results.push({name,status:'PASS',ms:Date.now()-started});}catch(e){results.push({name,status:e.message.startsWith('HARNESS')||e.name==='TimeoutError'||e.message.includes('strict mode violation')?'ERROR':'FAIL',message:e.message,ms:Date.now()-started});}finally{if(f){results.at(-1).apiCalls=f.calls;results.at(-1).blockedExternal=f.blocked;results.at(-1).pageErrors=f.errors;results.at(-1).requestFailures=f.requestFailures;await f.close();}console.log(results.at(-1).status+' '+name+(results.at(-1).message?' — '+results.at(-1).message.split('\n')[0]:''));}}
async function edit(f,text){const input=f.page.locator('[data-place-input]').first();if(!await input.isVisible())await f.page.locator('.place-name').first().click();await input.fill(text)}
async function chooseB(f){await edit(f,'地点B');await f.page.getByRole('button',{name:/地点B/}).filter({has:f.page.locator('b')}).first().click();await until(()=>f.calls.some(c=>c.path==='/api/route'&&c.query.destination==='110,30'),'B route requested');}
(async()=>{
 browser=await chromium.launch({...(process.env.CHROME_PATH ? {executablePath:process.env.CHROME_PATH} : {channel:'chrome'}),headless:true});
 for(const failure of [false,true])await test('route/'+(failure?'stale-failure':'stale-success'),async make=>{
  const gate=deferred();const a=stop('地点A',1);a.id='stop0';a.route=null;const f=await make({seed:trip([a]),api:c=>c.path==='/api/route'?(c.query.destination==='111,31'?gate.promise:route(999)):undefined});
  await until(()=>f.calls.some(c=>c.path==='/api/route'),'A route requested');await chooseB(f);await until(async()=>(await f.read()).destinations[0].route?.durationSeconds===999,'B result saved');
  gate.resolve(failure?{status:500,json:{error:{message:'旧A失败'}}}:route(111));await sleep(250);
  const d=(await f.read()).destinations[0];assert.equal(d.location.name,'地点B');assert.equal(d.route?.durationSeconds,999,'旧A响应不得覆盖/清掉B路线');
 });
 await test('search/uncommitted-edit-preserves-trip',async make=>{const f=await make();await edit(f,'尚未确认');const d=(await f.read()).destinations[0];assert.equal(d.location?.name,'地点A','候选确认前不得清掉已提交地点');assert.equal(d.route?.durationSeconds,900)});
 await test('search/stale-error-does-not-replace-new-results',async make=>{const gate=deferred();const f=await make({api:c=>c.path==='/api/poi'&&c.query.keywords==='旧查询'?gate.promise:undefined});await edit(f,'旧查询');await until(()=>f.calls.some(c=>c.query.keywords==='旧查询'),'old search');await edit(f,'新查询');await f.page.locator('[data-poi-results] button').filter({hasText:'新查询'}).waitFor();gate.resolve({status:500,json:{error:{message:'旧查询超时'}}});await sleep(150);assert.match(await f.page.locator('[data-poi-results]').innerText(),/新查询/,'旧失败不得覆盖新候选')});
 await test('search/late-result-after-clear-remains-hidden',async make=>{const gate=deferred();const f=await make({api:c=>c.path==='/api/poi'?gate.promise:undefined});await edit(f,'旧查询');await until(()=>f.calls.some(c=>c.path==='/api/poi'),'search');await edit(f,'');gate.resolve({status:500,json:{error:{message:'旧查询超时'}}});await sleep(150);assert.equal(await f.page.locator('[data-poi-results]').isVisible(),false)});
 const shared={v:1,s:{n:'分享起点',la:28,lo:105},dep:'2030-10-01T00:00:00Z',d:[{n:'分享目的地',la:32,lo:112,stay:[],r:{ds:123,dur:123}}]};const hash='#trip='+Buffer.from(JSON.stringify(shared)).toString('base64url');
 await test('share/cold-open-preserves-draft',async make=>{const f=await make({hash});assert.equal((await f.read()).startLocation.name,origin.name,'分享链接打开不得覆盖本地草稿')});
 await test('share/hashchange-preserves-draft',async make=>{const f=await make();await f.page.evaluate(hash=>location.hash=hash,hash);await sleep(450);assert.equal((await f.read()).startLocation.name,origin.name,'当前标签页打开分享也不得覆盖草稿')});
 await test('storage/snapshot-failure-no-success',async make=>{const f=await make();await f.page.evaluate(SK=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===SK)throw new DOMException('QA quota','QuotaExceededError');return original.call(this,k,v)}},SK);await f.page.getByRole('button',{name:'保存本方案',exact:true}).click();await f.page.getByRole('button',{name:'保存当前行程',exact:true}).click();await sleep(100);const text=await f.page.locator('body').innerText();assert.ok(!text.includes('已保存「'),'写入失败不得显示保存成功');assert.equal(await f.page.evaluate(SK=>localStorage.getItem(SK),SK),null);assert.equal(await f.page.getByRole('button',{name:'保存当前行程',exact:true}).isVisible(),true,'失败后保留保存界面以便重试')});
 await test('ai/close-prevents-late-cache-write',async make=>{const gate=deferred();const f=await make({ai:true,seed:trip([stop('测试公园')]),api:c=>c.path==='/api/scenic-analysis'?gate.promise:undefined});await f.page.locator('.poi-review-manual').first().click();await until(()=>f.calls.some(c=>c.path==='/api/scenic-analysis'),'AI started');await f.page.getByRole('button',{name:'关闭 AI 评价并清除该地点的缓存'}).click();gate.resolve({analysis:{review:'旧AI结果'}});await sleep(150);assert.ok(!(await f.page.locator('body').innerText()).includes('旧AI结果'));const cache=await f.page.evaluate(()=>JSON.parse(localStorage.getItem('drive-poi-review-v1')||'{}'));assert.equal(Object.keys(cache).length,0)});
 await test('ai/closed-stays-closed-after-reload',async make=>{const f=await make({ai:true,seed:trip([stop('测试公园')])});await f.page.locator('.poi-review-manual').first().click();await until(()=>f.calls.some(c=>c.path==='/api/scenic-analysis'),'AI requested');await f.page.getByRole('button',{name:'关闭 AI 评价并清除该地点的缓存'}).click();const before=f.calls.filter(c=>c.path==='/api/scenic-analysis').length;await f.page.reload({waitUntil:'domcontentloaded'});await sleep(250);assert.equal(f.calls.filter(c=>c.path==='/api/scenic-analysis').length,before,'刷新后不得重新自动请求已关闭POI')});
 await test('ai/close-removes-queued-job',async make=>{const gate=deferred();const f=await make({ai:true,seed:trip([stop('第一公园',0),stop('第二公园',1)]),api:c=>c.path==='/api/scenic-analysis'&&c.body.location.name==='第一公园'?gate.promise:undefined});await f.page.locator('#destination-stop0 .poi-review-manual').click();await f.page.locator('#destination-stop1 .poi-review-manual').click();await until(()=>f.calls.some(c=>c.path==='/api/scenic-analysis'),'first AI started');await f.page.locator('#destination-stop1').getByRole('button',{name:'关闭 AI 评价并清除该地点的缓存'}).click();gate.resolve({analysis:{review:'第一站评价'}});await sleep(1550);assert.equal(f.calls.filter(c=>c.path==='/api/scenic-analysis'&&c.body.location.name==='第二公园').length,0,'关闭排队项后不得发出请求')});
 await test('modal/refresh-focus-contained-and-restored',async make=>{const f=await make();await f.page.locator('#refreshRoutePreview').click();assert.equal(await f.page.evaluate(()=>document.querySelector('#refreshModal').contains(document.activeElement)),true,'打开后焦点须进入弹窗');for(let i=0;i<8;i++){await f.page.keyboard.press('Tab');assert.equal(await f.page.evaluate(()=>document.querySelector('#refreshModal').contains(document.activeElement)),true,'Tab不得进入背景')}await f.page.locator('#refreshCancel').click();assert.equal(await f.page.evaluate(()=>document.activeElement.id),'refreshRoutePreview')});
 await test('input/elevation-completion-keeps-focus',async make=>{const gate=deferred(),s=stop();s.elevationMeters=null;const f=await make({seed:trip([s]),api:c=>c.path==='/api/elevation'?gate.promise:undefined});await until(()=>f.calls.some(c=>c.path==='/api/elevation'),'elevation requested');await edit(f,'测试输入');gate.resolve({elevationMeters:123});await sleep(150);assert.equal(await f.page.evaluate(()=>document.activeElement.hasAttribute('data-place-input')),true,'海拔返回后仍保持输入焦点')});

 await test('ai/failure-never-retries-on-rerender',async make=>{const f=await make({ai:true,seed:trip([stop('测试公园')]),api:c=>c.path==='/api/scenic-analysis'?{status:503,json:{error:{message:'测试服务不可用'}}}:undefined});await f.page.locator('.poi-review-manual').click();await f.page.locator('.poi-review-error').waitFor();await sleep(3200);await f.page.locator('.stay-editor summary').click();for(let i=0;i<3;i++){await f.page.locator('[data-action="toggle-stay"][data-minutes="60"]').click();await sleep(50)}assert.equal(f.calls.filter(c=>c.path==='/api/scenic-analysis').length,1,'修改停留不得隐式重试失败AI');await f.page.locator('.poi-review-manual').click();await until(()=>f.calls.filter(c=>c.path==='/api/scenic-analysis').length===2,'explicit retry');});
 await test('control/search-selection-commits-new-location',async make=>{const f=await make();await chooseB(f);await until(async()=>(await f.read()).destinations[0].location?.name==='地点B','B committed');assert.equal((await f.read()).destinations[0].location.name,'地点B')});
 await test('control/snapshot-success-actually-persists',async make=>{const f=await make();await f.page.getByRole('button',{name:'保存本方案',exact:true}).click();await f.page.getByRole('button',{name:'保存当前行程',exact:true}).click();const saved=await f.page.evaluate(SK=>JSON.parse(localStorage.getItem(SK)||'[]'),SK);assert.equal(saved.length,1);assert.equal(saved[0].trip.s.n,origin.name)});
 await test('modal/share-focus-contained-and-restored',async make=>{const f=await make();await f.page.locator('#openShare').click();assert.equal(await f.page.evaluate(()=>document.querySelector('#shareModal').contains(document.activeElement)),true,'分享打开后焦点须进入弹窗');for(let i=0;i<12;i++){await f.page.keyboard.press('Tab');assert.equal(await f.page.evaluate(()=>document.querySelector('#shareModal').contains(document.activeElement)),true,'分享Tab不得进入背景')}await f.page.locator('#shareClose').click();assert.equal(await f.page.evaluate(()=>document.activeElement.id),'openShare')});

 await test('ai/initial-load-makes-no-request',async make=>{const f=await make({ai:true,seed:trip([stop('第一公园',0),stop('第二公园',1)])});await sleep(1600);assert.equal(f.calls.filter(c=>c.path.includes('analysis')).length,0);assert.equal(await f.page.locator('.poi-review-manual').count(),2)});
 await test('share/preview-is-readonly-and-shows-shared-trip',async make=>{const f=await make({hash,ai:true});assert.match(await f.page.locator('#timeline').innerText(),/分享目的地/);assert.equal(await f.page.locator('.shared-preview-banner').isVisible(),true);const enabled=await f.page.locator('.shell input,.shell button').evaluateAll(els=>els.filter(e=>!e.disabled&&!e.closest('.shared-preview-banner')&&e.id!=='backToTop').map(e=>({tag:e.tagName,text:e.textContent,id:e.id})));assert.deepEqual(enabled,[],'预览编辑/付费入口不得可用');assert.equal(f.calls.filter(c=>c.path==='/api/route'||c.path.includes('analysis')).length,0)});
 await test('share/save-copy-keeps-original-draft',async make=>{const f=await make({hash});await f.page.locator('[data-copy]').click();await f.page.getByRole('button',{name:'保存当前行程',exact:true}).click();const snaps=await f.page.evaluate(SK=>JSON.parse(localStorage.getItem(SK)||'[]'),SK);assert.equal(snaps.length,1);assert.equal(snaps[0].trip.s.n,'分享起点');assert.equal((await f.read()).startLocation.name,origin.name)});
 await test('share/exit-restores-original-draft',async make=>{const f=await make({hash});await f.page.locator('[data-exit]').click();await until(()=>f.page.locator('.shared-preview-banner').count().then(n=>n===0),'preview exited');assert.equal((await f.read()).startLocation.name,origin.name);assert.match(await f.page.locator('#timeline').innerText(),/地点A/)});
 await test('storage/snapshot-limit-preserves-all-12',async make=>{const f=await make();const entries=Array.from({length:12},(_,i)=>({id:'prior'+i,name:'方案'+i,savedAt:'2030-01-01T00:00:00Z',trip:shared}));await f.page.evaluate(({SK,entries})=>localStorage.setItem(SK,JSON.stringify(entries)),{SK,entries});await f.page.getByRole('button',{name:'保存本方案',exact:true}).click();await f.page.getByRole('button',{name:'保存当前行程',exact:true}).click();assert.deepEqual(await f.page.evaluate(SK=>JSON.parse(localStorage.getItem(SK)),SK),entries,'达到12上限不得静默删旧快照');assert.match(await f.page.locator('#tkToast').innerText(),/12/)});
 await test('search/cancel-restores-committed-location',async make=>{const f=await make();await edit(f,'未提交修改');await f.page.getByRole('button',{name:'取消修改',exact:true}).click();assert.equal((await f.read()).destinations[0].location.name,'地点A');assert.equal(await f.page.locator('[data-place-input]').inputValue(),'地点A');assert.equal(await f.page.locator('.place-name').innerText(),'地点A')});

 await test('edge/cancel-button-hit-target',async make=>{const f=await make();await edit(f,'未提交修改');await f.page.locator('[data-poi-results] button').waitFor();const b=f.page.locator('.poi-cancel');await b.scrollIntoViewIfNeeded();const sample=await b.evaluate(e=>{const r=e.getBoundingClientRect();return {rect:{x:r.x,y:r.y,w:r.width,h:r.height},hits:[.2,.5,.8].flatMap(x=>[.2,.5,.8].map(y=>{const hit=document.elementFromPoint(r.x+r.width*x,r.y+r.height*y);return {x,y,owned:!!hit&&(hit===e||e.contains(hit)),hit:hit?.outerHTML.slice(0,180)}}))}});assert.ok(sample.hits.some(h=>h.owned),'取消按钮9点均被遮挡: '+JSON.stringify(sample));await b.click();assert.equal((await f.read()).destinations[0].location.name,'地点A')});
 await test('edge/preview-slider-must-not-change-time',async make=>{const f=await make({hash});const before=await f.page.locator('#departureTime').inputValue();const slider=f.page.locator('#tfWhatifRange');if(await slider.isEnabled()){await slider.focus();await f.page.keyboard.press('ArrowRight');await f.page.keyboard.press('Tab');await sleep(200)}assert.equal(await f.page.locator('#departureTime').inputValue(),before,'共享预览滑杆不得改变出发时间');assert.equal(f.calls.filter(c=>c.path==='/api/route').length,0,'共享滑杆不得请求导航')});
 await test('edge/preview-dock-sort-must-not-mutate',async make=>{const h='#trip='+Buffer.from(JSON.stringify({...shared,d:[...shared.d,{n:'分享第二站',la:33,lo:113,stay:[],r:{ds:123,dur:123}}]})).toString('base64url');const f=await make({hash:h});await f.page.locator('#dockToggle').click();const names=await f.page.locator('.place-name').allTextContents();const sort=f.page.locator('.dock-sort');if(await sort.isVisible()&&await sort.isEnabled()){await sort.click();const items=f.page.locator('#tripDock .dock-item[data-id]');const a=await items.nth(0).boundingBox(),b=await items.nth(1).boundingBox();await f.page.mouse.move(a.x+a.width/2,a.y+a.height/2);await f.page.mouse.down();await sleep(220);await f.page.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:5});await f.page.mouse.up();await sleep(200)}assert.deepEqual(await f.page.locator('.place-name').allTextContents(),names,'共享预览排序不得改变站点顺序');assert.equal(f.calls.filter(c=>c.path==='/api/route').length,0,'共享预览排序不得请求导航')});
 await test('edge/card-refresh-only-current-leg',async make=>{const f=await make({seed:trip([stop('第一站',0),stop('第二站',1)])});await f.page.locator('#destination-stop1 .card-more summary').click();await f.page.locator('#destination-stop1 [data-action="retry-route"]').click();await until(()=>f.calls.some(c=>c.path==='/api/route'),'refresh route');await sleep(200);const routeCalls=f.calls.filter(c=>c.path==='/api/route');assert.equal(routeCalls.length,1,'卡片刷新只请求当前路段');assert.equal(routeCalls[0].query.destination,'111,31')});

 await test('boundary2/snapshot-modal-restores-opener',async make=>{const f=await make();const opener=f.page.getByRole('button',{name:'保存本方案',exact:true});await opener.click();assert.equal(await f.page.evaluate(()=>document.querySelector('#tkSnapshotModal').contains(document.activeElement)),true);assert.equal(await f.page.locator('#tkSnapshotModal .tk-save-row input').evaluate(e=>e===document.activeElement),true,'快照打开后焦点须进入方案名称输入');await f.page.locator('#tkSnapshotModal .tk-close').click();assert.equal(await opener.evaluate(e=>e===document.activeElement),true,'关闭快照弹窗后焦点须归还保存本方案按钮')});
 await test('boundary2/share-replace-backup-failure-preserves-draft',async make=>{const f=await make({hash});await f.page.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='drive-timeline-load-undo-v1')throw new DOMException('QA quota','QuotaExceededError');return original.call(this,k,v)}});f.page.once('dialog',d=>d.accept());await f.page.locator('[data-replace]').click();await sleep(550);assert.equal((await f.read()).startLocation.name,origin.name);assert.equal(await f.page.locator('.shared-preview-banner').isVisible(),true);assert.match(await f.page.locator('#tkToast').innerText(),/无法备份/)});
 await test('boundary2/share-replace-and-undo',async make=>{const f=await make({hash});f.page.once('dialog',d=>d.accept());await f.page.locator('[data-replace]').click();await until(()=>f.page.locator('.shared-preview-banner').count().then(n=>n===0),'accepted preview');assert.equal((await f.read()).startLocation.name,'分享起点');await f.page.locator('#undoSnackbar .undo-snackbar-action').click();await until(async()=>(await f.read()).startLocation.name===origin.name,'undo original');assert.equal((await f.read()).destinations[0].location.name,'地点A')});
 await test('boundary2/search-escape-invalidates-late-response',async make=>{const gate=deferred();const f=await make({api:c=>c.path==='/api/poi'?gate.promise:undefined});await edit(f,'取消前查询');await until(()=>f.calls.some(c=>c.path==='/api/poi'),'search started');await f.page.keyboard.press('Escape');gate.resolve({pois:[loc('迟到地点')]});await sleep(150);assert.equal((await f.read()).destinations[0].location.name,'地点A');assert.equal(await f.page.locator('[data-poi-results]').isVisible(),false);assert.equal(await f.page.locator('.place-name').innerText(),'地点A')});
 await test('boundary2/start-search-cancel-keeps-start-and-route',async make=>{const f=await make();await f.page.locator('#startPlaceInput').fill('新起点草稿');assert.equal((await f.read()).startLocation.name,origin.name);assert.equal((await f.read()).destinations[0].route.durationSeconds,900);await f.page.keyboard.press('Escape');assert.equal(await f.page.locator('#startPlaceInput').inputValue(),origin.name)});
 await test('boundary2/composition-defers-search-until-end',async make=>{const f=await make();await f.page.locator('.place-name').click();await f.page.locator('[data-place-input]').evaluate(e=>{e.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));e.value='北京';e.dispatchEvent(new InputEvent('input',{bubbles:true,data:'北京',inputType:'insertCompositionText',isComposing:true}))});await sleep(450);assert.equal(f.calls.filter(c=>c.path==='/api/poi').length,0,'组合输入期间不搜索');assert.equal((await f.read()).destinations[0].location.name,'地点A');await f.page.locator('[data-place-input]').evaluate(e=>e.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:'北京'})));await until(()=>f.calls.some(c=>c.path==='/api/poi'),'composition end search');assert.equal(f.calls.filter(c=>c.path==='/api/poi').length,1)});
 await test('boundary2/draft-storage-failure-warns-and-recovers',async make=>{const f=await make();await f.page.evaluate(K=>{const original=Storage.prototype.setItem;globalThis.qaRestoreStorage=()=>Storage.prototype.setItem=original;Storage.prototype.setItem=function(k,v){if(k===K)throw new DOMException('QA quota','QuotaExceededError');return original.call(this,k,v)}},K);await f.page.locator('#addDestination').click();assert.equal(await f.page.locator('#persistWarning').isVisible(),true);assert.equal((await f.read()).destinations.length,1);assert.equal(await f.page.locator('.destination-card').count(),2);await f.page.evaluate(()=>qaRestoreStorage());await f.page.locator('#addDestination').click();assert.equal((await f.read()).destinations.length,3);assert.equal(await f.page.locator('#persistWarning').isVisible(),false)});

 await test('network/refresh-failure-retains-known-route',async make=>{const f=await make({api:c=>c.path==='/api/route'?{status:503,json:{error:{message:'隔离服务故障'}}}:undefined});await f.page.locator('.card-more summary').click();await f.page.locator('.card-more [data-action="retry-route"]').click();await until(async()=>!!(await f.read()).destinations[0].routeError,'refresh failed');const d=(await f.read()).destinations[0];assert.equal(d.route.durationSeconds,900);assert.match(d.routeError,/保留上次导航数据/);assert.equal(!!d.routeLoading,false);assert.match(await f.page.locator('.route-status').innerText(),/保留上次导航数据/)});
 await test('network/hung-route-times-out-and-can-retry',async make=>{const gate=deferred(),a=stop();a.route=null;let n=0;const f=await make({clock:true,seed:trip([a]),api:c=>c.path==='/api/route'?(++n===1?gate.promise:route(888)):undefined});await until(()=>n===1,'hung route started');await f.page.clock.fastForward(20050);await until(async()=>!!(await f.read()).destinations[0].routeError,'route timeout');const d=(await f.read()).destinations[0];assert.match(d.routeError,/超时/);assert.equal(!!d.routeLoading,false);await f.page.locator('.card-more summary').click();await f.page.locator('.card-more [data-action="retry-route"]').click();await until(async()=>(await f.read()).destinations[0].route?.durationSeconds===888,'retry recovered');assert.equal((await f.read()).destinations[0].routeError,undefined)});
 await test('network/stop-hung-queue-rejects-late-response',async make=>{const gate=deferred(),a=stop('第一站',0),b=stop('第二站',1);a.route=b.route=null;const f=await make({seed:trip([a,b]),api:c=>c.path==='/api/route'?gate.promise:undefined});await until(()=>f.calls.some(c=>c.path==='/api/route'),'hung request');await f.page.getByRole('button',{name:'停止刷新',exact:true}).click();await until(()=>f.requestFailures.some(r=>r.url.includes('/api/route')),'fetch aborted');gate.resolve(route(111));await sleep(150);const d=(await f.read()).destinations;assert.ok(d.every(x=>!x.route&&!x.routeLoading));assert.equal(f.calls.filter(c=>c.path==='/api/route').length,1,'停止后不请求下一站');assert.equal(await f.page.locator('.route-map-loading').isVisible(),false)});
 await test('network/new-rebuild-aborts-previous-fetch',async make=>{const gate=deferred(),a=stop('地点A',1);a.id='stop0';a.route=null;const f=await make({seed:trip([a]),api:c=>c.path==='/api/route'?(c.query.destination==='111,31'?gate.promise:route(999)):undefined});await until(()=>f.calls.some(c=>c.path==='/api/route'),'old request');await chooseB(f);await until(()=>f.requestFailures.some(r=>r.url.includes('/api/route')&&r.url.includes('111%2C31')),'old network request aborted');gate.resolve(route(111));await until(async()=>(await f.read()).destinations[0].route?.durationSeconds===999,'B completed');await sleep(100);assert.equal((await f.read()).destinations[0].route.durationSeconds,999)});
 await test('network/total-ai-cancel-late-response-and-retry',async make=>{const gate=deferred();let n=0;const f=await make({ai:true,api:c=>c.path==='/api/ai-analysis'?(++n===1?gate.promise:{fingerprint:c.body.fingerprint,analysis:{headline:'新总评',overview:'新结果'}}):undefined});await f.page.locator('#openAiAnalysis').click();await f.page.locator('#aiConfirm').click();await until(()=>n===1,'AI hung');await f.page.locator('#cancelAiAnalysis').click();await until(()=>f.page.locator('#openAiAnalysis').isEnabled(),'AI UI recovered');gate.resolve({fingerprint:f.calls.find(c=>c.path==='/api/ai-analysis').body.fingerprint,analysis:{headline:'迟到总评',overview:'旧结果'}});await sleep(100);assert.ok(!(await f.page.locator('body').innerText()).includes('迟到总评'));assert.equal(await f.page.evaluate(()=>localStorage.getItem('drive-timeline-ai-analysis-v1')),null);assert.match(await f.page.locator('#aiAnalysisHint').innerText(),/已停止/);await f.page.locator('#openAiAnalysis').click();await f.page.locator('#aiConfirm').click();await until(()=>f.page.locator('#aiAnalysisResult').innerText().then(t=>t.includes('新总评')),'AI retry succeeded')});
 await test('network/total-ai-hung-times-out',async make=>{const gate=deferred();const f=await make({clock:true,ai:true,api:c=>c.path==='/api/ai-analysis'?gate.promise:undefined});await f.page.locator('#openAiAnalysis').click();await f.page.locator('#aiConfirm').click();await until(()=>f.calls.some(c=>c.path==='/api/ai-analysis'),'AI hung');await f.page.clock.fastForward(110050);await until(()=>f.page.locator('#openAiAnalysis').isEnabled(),'AI timeout recovered');assert.match(await f.page.locator('#aiAnalysisHint').innerText(),/超时/);assert.equal(await f.page.locator('#cancelAiAnalysis').isVisible(),false)});
 await test('network/search-timeout-preserves-committed-place',async make=>{const gate=deferred();const f=await make({clock:true,api:c=>c.path==='/api/poi'?gate.promise:undefined});await edit(f,'永久等待');await f.page.clock.fastForward(400);await until(()=>f.calls.some(c=>c.path==='/api/poi'),'search hung');await f.page.clock.fastForward(20050);await until(()=>f.page.locator('[data-poi-results]').innerText().then(t=>t.includes('超时')),'search timeout');assert.equal((await f.read()).destinations[0].location.name,'地点A');assert.equal((await f.read()).destinations[0].route.durationSeconds,900)});

 await test('final/template-preview-preserves-draft-and-no-services',async make=>{const f=await make({ai:true});const before=await f.read();await f.page.getByRole('button',{name:'预览示例',exact:true}).click();await f.page.locator('#tkTemplateModal .tk-tpl-card').first().click();await f.page.locator('.shared-preview-banner').waitFor();assert.match(await f.page.locator('.shared-preview-banner h2').innerText(),/示例.*只读/);assert.deepEqual(await f.read(),before,'模板预览不写原草稿');assert.equal(f.calls.filter(c=>c.path==='/api/route'||c.path.includes('analysis')).length,0,'预览不得导航或AI');assert.equal(await f.page.locator('[data-replace]').innerText(),'采用示例')});
 await test('final/template-adoption-backs-up-original',async make=>{const f=await make();const before=await f.read();await f.page.getByRole('button',{name:'预览示例',exact:true}).click();await f.page.locator('#tkTemplateModal .tk-tpl-card').first().click();await f.page.locator('.shared-preview-banner').waitFor();assert.deepEqual(await f.read(),before);f.page.once('dialog',d=>d.accept());await f.page.locator('[data-replace]').click();await until(()=>f.page.locator('.shared-preview-banner').count().then(n=>n===0),'sample accepted');const backup=await f.page.evaluate(()=>JSON.parse(localStorage.getItem('drive-timeline-load-undo-v1')));assert.deepEqual(JSON.parse(backup.trip),before,'采用前完整备份');assert.notEqual((await f.read()).startLocation.name,origin.name);assert.ok((await f.read()).destinations.length>1)});
 for(const fail of [false,true])await test('final/snapshot-explicit-replace-'+(fail?'quota-preserves-original':'success'),async make=>{const f=await make();const entries=Array.from({length:12},(_,i)=>({id:'prior'+i,name:'方案'+i,savedAt:'2030-01-01T00:00:00Z',trip:shared}));await f.page.evaluate(({SK,entries,fail})=>{localStorage.setItem(SK,JSON.stringify(entries));if(fail){const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===SK)throw new DOMException('QA quota','QuotaExceededError');return original.call(this,k,v)}}},{SK,entries,fail});await f.page.getByRole('button',{name:'保存本方案',exact:true}).click();await f.page.getByRole('combobox',{name:'新建或替换已保存方案'}).selectOption('prior5');await f.page.getByRole('textbox',{name:'方案名称',exact:true}).fill('明确替换5');await f.page.getByRole('button',{name:'保存当前行程',exact:true}).click();const saved=await f.page.evaluate(SK=>JSON.parse(localStorage.getItem(SK)),SK);if(fail){assert.deepEqual(saved,entries,'Quota失败所有原快照必须保持');assert.match(await f.page.locator('#tkToast').innerText(),/失败/);assert.equal(await f.page.getByRole('button',{name:'保存当前行程',exact:true}).isVisible(),true)}else{assert.equal(saved.length,12);assert.equal(saved[5].id,'prior5');assert.equal(saved[5].name,'明确替换5');assert.equal(saved[5].trip.s.n,origin.name);assert.deepEqual(saved.filter((_,i)=>i!==5),entries.filter((_,i)=>i!==5))}});
 await test('final/shared-shortcuts-all-disabled',async make=>{const f=await make({hash});const buttons=f.page.locator('.planning-shortcuts button');assert.deepEqual(await buttons.allTextContents(),['添加下一站','查看地图','预览示例']);assert.equal(await buttons.evaluateAll(es=>es.every(e=>e.disabled)),true,'共享下三快捷按钮禁用')});
 await browser.close();const report={createdAt:new Date().toISOString(),source,sha,environment:'Desktop Chrome, isolated 390x844 mobile context; not iOS Safari; external fonts/scripts blocked',networkPolicy:'Every request fulfilled from in-memory local source, JSON mock, or aborted. No route.continue/fallback. AI only mock.',summary:results.reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{}),results};fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(report,null,2));console.log(JSON.stringify(report.summary));process.exitCode=results.some(r=>r.status==='ERROR')?2:results.some(r=>r.status==='FAIL')?1:0;
})().catch(async e=>{console.error(e);await browser?.close();process.exitCode=2});
