/* Real html2canvas, mocked navigation/AI, never the user's browser/profile. */
const {chromium}=require('playwright'), fs=require('node:fs'), path=require('node:path'), assert=require('node:assert/strict');
const root=path.join(__dirname,'..'), lib=process.env.HTML2CANVAS_PATH||'/tmp/roadbook-html2canvas-1.4.1.min.js';
const start={name:'测试起点',latitude:29,longitude:106,poiId:'origin'};
const trip={startLocation:start,startSearchText:start.name,initialDepartureTime:'2030-09-30T10:00:00Z',destinations:Array.from({length:8},(_,i)=>({id:'stop'+i,location:{name:'测试公园'+i,address:'用于回归测试的长地址',latitude:30+i/10,longitude:107+i/10,poiId:'poi'+i},elevationMeters:3000,route:{durationSeconds:18000,distanceMeters:300000,strategy:'highway'},selectedStayButtons:[480],stayMode:'duration'}))};
trip.destinations[0].location.name='大柴旦光影之城景区草原野奢营地（北门游客中心停车场）';
(async()=>{ const browser=await chromium.launch({channel:'chrome',headless:true});
 try {const context=await browser.newContext({viewport:{width:393,height:844},serviceWorkers:'block'}),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await context.addInitScript(trip=>localStorage.setItem('drive-timeline-trip-v1',JSON.stringify(trip)),trip);
 await context.route('**/*',async r=>{const u=new URL(r.request().url());
  if(u.href.includes('html2canvas@1.4.1/')) return r.fulfill({body:fs.readFileSync(lib),contentType:'application/javascript'});
  if(u.hostname!=='local.test') return r.abort();
  if(u.pathname==='/config.js')return r.fulfill({body:'globalThis.DRIVE_AI_ENABLED=false;',contentType:'application/javascript'});
  if(u.pathname==='/api/trip-share')return r.fulfill({json:{code:'AB2CD3',expiresAt:Date.now()+7*86400000}});
  if(u.pathname.startsWith('/api/'))return r.fulfill({json:{elevationMeters:100}});
  const file=path.join(root,u.pathname==='/'?'index.html':u.pathname.slice(1)); if(!fs.existsSync(file))return r.abort();
  return r.fulfill({body:fs.readFileSync(file),contentType:file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html'});
 });
 await page.goto('https://local.test/');await page.locator('#openShare').click();
 await page.waitForFunction(()=>!document.querySelector('#shareDownload').disabled,{},{timeout:60000});
 assert.equal(await page.locator('#shareIncludeMap').isChecked(),false);
 assert.ok(await page.locator('#shareParts button').count()>1,'long itinerary split into pages');
 assert.equal(await page.locator('#sharePoster .rb-station').count(),9);
 const reading=await page.locator('#sharePoster').evaluate(el=>{
   const size=s=>parseFloat(getComputedStyle(el.querySelector(s)).fontSize);
   return {width:el.offsetWidth,overflow:el.scrollWidth>el.offsetWidth,meta:size('.rb-meta'),time:size('.rb-time-line strong'),hint:getComputedStyle(el.querySelector('.rb-hints .rb-chip')).backgroundColor,columns:getComputedStyle(el.querySelector('.rb-stats')).gridTemplateColumns.split(' ').length};
 });
 assert.equal(reading.width,400);assert.equal(reading.overflow,false);assert.equal(reading.meta,14);assert.equal(reading.time,26);assert.equal(reading.columns,2);assert.equal(reading.hint,'rgba(0, 0, 0, 0)');
 assert.equal(await page.locator('.rb-station-head h3').nth(1).evaluate(el=>el.scrollWidth<=el.clientWidth),true,'long names wrap within the exported card');
 const download=page.waitForEvent('download');await page.locator('#shareDownload').click();await (await download).saveAs('/tmp/roadbook-export-1.png');
 const second=page.waitForEvent('download');await page.locator('#shareParts button').nth(1).click();await (await second).saveAs('/tmp/roadbook-export-2.png');
 const png=fs.readFileSync('/tmp/roadbook-export-1.png');assert.ok(png.readUInt32BE(16)<=1200);assert.ok(png.readUInt32BE(20)>7244);assert.ok(png.readUInt32BE(20)<=16001);
 const ratio=png.readUInt32BE(20)/png.readUInt32BE(16);
 const expected=await page.locator('#sharePoster').evaluate(el=>el.scrollHeight/400);
 assert.ok(Math.abs(ratio-expected)<.03,'complete poster aspect ratio, no crop');
 assert.equal(await page.getByRole('button',{name:'放大阅读',exact:true}).count(),0);
 assert.equal(await page.locator('#shareIncludeAddress').count(),0);
 assert.equal(await page.locator('.share-name-shortcuts').count(),0);
 assert.match(await page.locator('.rb-brand').innerText(),/分享码：AB2CD3/);
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async t=>{window.testCopied=t;}}}));
 await page.locator('#tkCopyLink').click();assert.equal(await page.evaluate(()=>window.testCopied),'https://local.test/?s=AB2CD3');
 await page.locator('#tkCopyCode').click();assert.equal(await page.evaluate(()=>window.testCopied),'AB2CD3');
 await page.screenshot({path:'/tmp/roadbook-share-redesign.png'});
 await page.locator('#shareNameInput').fill('新版长图');await page.locator('#shareClose').click();await page.locator('#openShare').click();
 await page.waitForFunction(()=>!document.querySelector('#shareDownload').disabled,{},{timeout:60000});assert.equal(await page.locator('#sharePoster h1').innerText(),'我的自驾行程');
 assert.deepEqual(errors,[]); console.log('PASS complete PNG, segmented alternatives, share-code subtitle, direct short link/code copy, removed controls, session cancellation');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
